config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :comentarios
  resources :perfis
  get '/user_details', to: 'accounts#user_details'
  get '/posts_details', to: 'accounts#posts_details'
  resources :posts do
    resources :comentarios
  end
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    mailer: "users/mailer",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    passwords: "users/passwords",
   }

   get '/change_password', to: 'passwords#edit', as: 'change_password'
   patch '/update_password', to: 'passwords#update', as: 'update_password'

  get "home/index"
  root "home#index"
  get '/search_suggestions', to: 'home#search_suggestions'
  get '/upload_post', to: 'posts#upload_post'
  match '/create_upload_post', to: 'posts#create_upload_post' , via: [:get, :post]

end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[ show edit update destroy ]

  # GET /comentarios or /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1 or /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios or /comentarios.json
  def create
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.build(comentario_params)

    if @comentario.save
      render turbo_stream: turbo_stream.append("comments", partial: "comentario", locals: { comentario: @comentario })
    else
     render turbo_stream: turbo_stream.replace("comment_form", partial: "form"), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comentarios/1 or /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to  post_path(@comentario.post), notice: I18n.t('comentarios.atualizado') }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    post = @comentario.post
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to post_path(post), notice: I18n.t('comentarios.deletado') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:post_id, :autor, :body, :user_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<div id="<%= dom_id comentario %>">
  <p>
    <strong>Post:</strong>
    <%= comentario.post_id %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= comentario.autor %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comentario.body %>
  </p>

</div>

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario) do |form| %>
  <% if comentario.errors.any? %>
    <div class="container">
      <% comentario.errors.full_messages.each do |error_message| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= error_message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="card bg-light">
    <div class="card-body">
      <%= form.text_area :body, class: "form-control mb-3", rows: "3"%>
      <div>
        <%= form.submit t('views.enviar_comentario'), class: "btn btn-outline-dark mb-2" %>
        <%= link_to t('views.cancelar'), post_path(comentario.post), class: "btn btn-outline-primary mb-2" %>
        <%= form.hidden_field :autor, value: current_user.nil? ? "Anonimo" : current_user.perfil.nome.capitalize %>
        <%= form.hidden_field :post_id %>
        <%= form.hidden_field :user_id, value: current_user.nil? ? "" : current_user.id %>
      </div>
    </div>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render "form", comentario: @comentario %>

<br>

app/views/comentarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comentarios</h1>

<div id="comentarios">
  <% @comentarios.each do |comentario| %>
    <%= render comentario %>
    <p>
      <%= link_to "Show this comentario", comentario %>
    </p>
  <% end %>
</div>

<%= link_to "New comentario", new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render "form", comentario: @comentario %>

app/views/comentarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comentario %>

<div>
  <%= link_to "Edit this comentario", edit_comentario_path(@comentario) %> |
  <%= link_to "Back to comentarios", comentarios_path %>

  <%= button_to "Destroy this comentario", @comentario, method: :delete %>
</div>