config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :comentarios
  resources :perfis
  get '/user_details', to: 'accounts#user_details'
  get '/posts_details', to: 'accounts#posts_details'
  resources :posts do
    resources :comentarios
  end
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    mailer: "users/mailer",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    passwords: "users/passwords",
   }

   get '/change_password', to: 'passwords#edit', as: 'change_password'
   patch '/update_password', to: 'passwords#update', as: 'update_password'

  get "home/index"
  root "home#index"
  get '/search_suggestions', to: 'home#search_suggestions'
  get '/upload_post', to: 'posts#upload_post'
  match '/create_upload_post', to: 'posts#create_upload_post' , via: [:get, :post]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy
  has_many :tag_posts, dependent: :destroy
  has_many :tags, through: :tag_posts
  validates :titulo, presence: true
  validates :body, presence: true
  validates :tag_ids, presence: true, on: :create
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def upload_post
    @post = Post.new
    flash[:notice] = I18n.t('views.multiplos_posts')
  end

  def create_upload_post
    if params[:post][:posts].present?
      @posts = []
      params[:post][:posts].shift
      params[:post][:posts].each do |post|
        post_data = ::Upload::ProcessTxt.new(post).execute
        post_data[:user_id] = params[:post][:user_id]
        @posts << post_data
      end
      
      # Processar os posts primeiro
      @posts.each do |post|
        ProcessPostsWorker.perform_async(post.as_json)
      end
      # Enviar uma notificação inicial
      ActionCable.server.broadcast(
        "upload_notifications_#{params[:post][:user_id]}",
        {
          message: "Iniciando processamento de #{@posts.size} posts...",
          status: 'info'
        }
      )
    else
      flash[:error] = I18n.t("posts.erro")
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @tags = TagPost.where(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: I18n.t("posts.criado") }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: I18n.t("posts.atualizado") }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_details_path, notice: I18n.t("posts.deletado") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :titulo, :body, :tag_ids => [], :posts => [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for post do |form| %>
  <% if post.errors.any? %>
    <div class="container">
      <% post.errors.full_messages.each do |error_message| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= error_message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="container px-5 my-5">
    <h1 class="display-5 fw-bolder"><%= %></h1>
    <div class="card col-10">
      <div class="card-body">
        <%= form_with(model: @post, local: true) do |form| %>
          <%= form.hidden_field :user_id, value: current_user.id %>

          <div class="mb-3">
            <%= form.label :titulo , class: "form-label" %>
            <%= form.text_field :titulo, class: "form-control", required: true %>
          </div>

          <div class="mb-3">
            <%= form.label :body, class: "form-label" %>
            <%= form.text_area :body, class: "form-control", rows: 8, id: "text-body", required: true %>
          </div>

          <div class="mb-3 col-md-4">
            <%= form.label "Tags" %>
              <i class="bi bi-question-circle-fill" data-bs-toggle="tooltip" data-bs-placement="top"data-bs-title="<%= t('views.selecionar_tags') %>"></i>
            <%= form.select :tag_ids, options_for_select(Tag.order(:nome).map { |tag| [tag.nome, tag.id] }, params[:tag_ids]), { include_hidden: false }, { class: "form-select mt-3", multiple: true, id: "tag-dropdown", required: true } %>
          </div>
          <div id="selected-tags"></div>
          <div class="mb-3">
            <%= form.submit class: "btn btn-outline-dark", data: { turbo: false } %>
            <%= link_to "Home", home_index_path, class: "btn btn-outline-dark ms-2", data: { turbo: false } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/js/bootstrap-select.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<% end %>
<script>
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
  const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Blog Post - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
  </head>
  <body>
    <div class="container mt-5">
      <div class="row">
        <div class="col-lg-8">
          <!-- Post content-->
          <article>
            <!-- Post header-->
            <header class="mb-4">
              <!-- Post title-->
              <h1 class="fw-bolder mb-1"><%= @post.titulo%></h1>
              <!-- Post meta content-->
              <div class="text-muted fst-italic mb-2">
                  <%= t('views.posted') %> <%= l(@post.created_at) %> 
                  <%= t('views.by') %> <%= @post.user.perfil.nome.capitalize rescue nil %>
              </div>
              <!-- Post categories-->
              <% @tags.each do |tag|%>
                <a class="badge bg-secondary text-decoration-none link-light" href="#!"><%= tag.tag.nome %></a>
              <% end %>
            </header>
            <section class="mb-5">
              <p class="fs-5 mb-4"><%= @post.body %></p>
              <% if user_signed_in? && current_user.id == @post.user_id %>
              <div class="d-flex justify-content-start">
                <%= link_to t('views.editar_post'), edit_post_path(@post) , class: "btn btn-outline-primary ", data: { turbo: false } %>
                <%= button_to t('views.deletar_post'), @post, method: :delete, data: { turbo_confirm: t('views.mensagem_deletar') }, class: "btn btn-outline-danger", style: "margin-left: 10px;" %>
              </div>
              <% end %>
            </section>
          </article>
          <section class="mb-5">
            <div class="card bg-light">
              <div class="card-body">
                <turbo-frame id="comment_form">
                  <%= form_with(model: [@post, Comentario.new], id: "new_comment", data: { controller: "form", action: "turbo:submit-end->form#reset" }) do |form| %>
                    <%= form.text_area :body, class: "form-control mb-3", rows: "3", placeholder: t('views.junte_se') %>
                    <div>
                      <%= form.submit t('views.enviar_comentario'), class: "btn btn-outline-dark mb-2" %>
                      <%= form.hidden_field :autor, value: current_user.nil? ? "Anonimo" : current_user.perfil.nome.capitalize %>
                      <%= form.hidden_field :user_id, value: current_user.nil? ? "" : current_user.id %>
                    </div>
                  <% end %>
                </turbo-frame>

                 <div class="comments-container" style="max-height: 300px; overflow-y: auto;">
                  <% if @post.comentarios.any? %>
                    <% @post.comentarios.each do |comentario| %>
                      <div class="card mb-4">
                        <div class="card-body">
                <turbo-frame id="comments">
                          <div class="d-flex mb-2">
                            <div class="flex-shrink-0">
                            <%= exibir_avatar(comentario.user_id, 45, 50) %>
                            </div>
                            <div class="ms-3">
                              <div class="fw-bold"><%= comentario.autor %></div>
                              <%= comentario.body %>
                            </div>
                          </div>
                </turbo-frame>
                          <% if user_signed_in? && current_user.id == comentario.user_id%>
                            <div class="ms-5 mt-2 d-flex justify-content-end">
                              <%= link_to edit_comentario_path(comentario), class: "btn btn-outline-primary btn-sm me-2", style: "width: 32px; height: 31px" do  %>
                                <i class="bi bi-pencil-square"></i>
                              <% end %>
                              <%= button_to comentario, method: :delete, data: { turbo_confirm: t('views.mensagem_deletar') }, class: "btn btn-outline-danger btn-sm" do %>
                                <i class="bi bi-trash"></i>
                              <% end %>
                            </div>
                          <% elsif user_signed_in? && current_user.id == @post.user_id %>
                            <div class="ms-5 mt-2 d-flex justify-content-end">
                              <%= button_to comentario, method: :delete, data: { turbo_confirm: t('views.mensagem_deletar') }, class: "btn btn-outline-danger btn-sm" do %>
                                <i class="bi bi-trash"></i>
                              <% end %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <div class="card mb-4">
                      <div class="card-body">
                        <div class="d-flex mb-2">
                          <div class="ms-3">
                            <div class="fw-bold"><%= t('views.nenhum_comentario') %></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/upload_post.html.erb
<!-- app/views/posts/new.html.erb -->
<div class="container px-md-5 my-5">
  <h1 class="display-5 fw-bolder text-center">Upload Post</h1>
  <div class="card col-md-6 mx-auto">
    <div class="card-body">
      <%= form_with(model: @post, url: create_upload_post_path, method: :post, multipart: true, data: {turbo: false}) do |form| %>
        <% if @post.errors.any? %>
          <div class="container">
            <% @post.errors.full_messages.each do |error_message| %>
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <%= error_message %>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            <% end %>
          </div>
        <% end %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <div class="mb-3">
          <h4 class="text-center"><%= t('buttons.escolher_upload') %></h4>
          <%= form.file_field :posts, class: "d-none", id: "posts_input", multiple: true %>
          <%= button_tag t('buttons.escolher_upload'), type: 'button', class: "w-100 btn btn-outline-primary mb-1", onclick: "document.getElementById('posts_input').click();" %>
          <%= form.submit "Upload", class: "btn btn-outline-success mt-2" %>
          <%= link_to "Home", home_index_path, class: "btn btn-outline-dark mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.14.0-beta2/js/bootstrap-select.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>