config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :comentarios
  resources :perfis
  get '/user_details', to: 'accounts#user_details'
  get '/posts_details', to: 'accounts#posts_details'
  resources :posts do
    resources :comentarios
  end
  
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    mailer: "users/mailer",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    passwords: "users/passwords",
   }

   get '/change_password', to: 'passwords#edit', as: 'change_password'
   patch '/update_password', to: 'passwords#update', as: 'update_password'

  get "home/index"
  root "home#index"
  get '/search_suggestions', to: 'home#search_suggestions'
  get '/upload_post', to: 'posts#upload_post'
  match '/create_upload_post', to: 'posts#create_upload_post' , via: [:get, :post]

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def user_details
    @user = current_user
    @post = Post.where(user_id: @user.id)
    @post_count = @post.count
    @comentarios_count =  Comentario.where(user_id: @user.id).count
  end

  def posts_details
    @posts = Post.where(user_id: current_user.id).order("created_at DESC")
    search = params[:search]
    tags = Tag.where("nome ILIKE ?", "%#{search}%").pluck(:id) if search.present?
    @posts = @posts.tag_ids(tags) if tags.present?
    @posts = @posts.paginate(page: params[:page], per_page: 3)
  end
end

app/views/accounts/posts_details.html.erb
<!DOCTYPE html>
  <body>
  
    <div class="container mt-5">
      <br>
      <div class="row">
        <div class="col-lg-8">
          <!-- Post content-->
          <article>
            <!-- Post header-->
            <header class="mb-4">
              <!-- Post title-->
              <br>
              <% if user_signed_in? %>
                <%= link_to I18n.translate('buttons.new_post'),new_post_path, class: "btn btn-outline-success ms-1", data: { turbo: false } %>
                <%= link_to "Upload Post",upload_post_path, class: "btn btn-outline-primary ms-1", data: { turbo: false } %>
              <% end %>
              <br>
              <br>
              <% @posts.each do |post| %>
                <h3 class="fw-bolder mb-1"><%=post.titulo.capitalize%></h3>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">
                  <%= t('views.posted') %> <%= l(post.created_at) %> 
                  <%= t('views.by') %> <%= post.user.perfil.nome.capitalize %>
                </div>

                <!-- Post categories-->
              <% post.tags.each do |tag|%>
                <a class="badge bg-secondary text-decoration-none link-light" href="#!"><%= tag.nome %></a>
              <% end %>
              </header>
              <section>
                <p class="fs-5"><%= post.body %></p>
              </section>
               <div class="d-flex justify-content-start mb-4">
                <%= link_to t('buttons.comment'), post_path(post), class: "btn btn-outline-dark" %>
                <% if user_signed_in? && current_user.id == post.user_id %>
                  <%= button_to t('buttons.deletar_post'), post, method: :delete, data: { turbo_confirm: t('views.mensagem_deletar') }, class: "btn btn-outline-danger", style: "margin-left: 10px;" %>
                <% end %>
              </div>
            </article>
            <section class="mb-5">
              <div class="card bg-light">
                <div class="card-body">
                  <div class="comments-container" style="max-height: 300px; overflow-y: auto;">
                  <% if post.comentarios.any? %>
                    <% post.comentarios.each do |comentario| %>
                      <div class="card mb-4">
                        <div class="card-body">
                          <div class="d-flex mb-2">
                            <div class="flex-shrink-0">
                              <%= exibir_avatar(comentario.user_id, 45, 50) %>
                            </div>
                            <div class="ms-3">
                              <div class="fw-bold"><%= comentario.autor %></div>
                              <%= comentario.body %>
                            </div>
                          </div>
                          <% if user_signed_in? && current_user.id == comentario.user_id%>
                            <div class="ms-5 mt-2 d-flex justify-content-end">
                              <%= link_to edit_comentario_path(comentario), class: "btn btn-outline-primary btn-sm me-2", style: "width: 32px; height: 31px" do  %>
                                <i class="bi bi-pencil-square"></i>
                              <% end %>
                              <%= button_to comentario, method: :delete, data: { turbo_confirm: "Tem certeza que deseja excluir este comentário?" }, class: "btn btn-outline-danger btn-sm" do %>
                                <i class="bi bi-trash"></i>
                              <% end %>
                            </div>
                          <% elsif user_signed_in? && current_user.id == post.user_id %>
                            <div class="ms-5 mt-2 d-flex justify-content-end">
                              <%= button_to comentario, method: :delete, data: { turbo_confirm: t('views.deletar_comentario') }, class: "btn btn-outline-danger btn-sm" do %>
                                <i class="bi bi-trash"></i>
                              <% end %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <div class="card mb-4">
                      <div class="card-body">
                        <div class="d-flex mb-2">
                          <div class="ms-3">
                            <div class="fw-bold"><%= t('views.nenhum_comentario') %></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  </div>
                </div>
              </div>
            </section>
          <% end %>
          <div class="digg_pagination mb-5">
            <%= will_paginate @posts , page_links: true %>
          </div>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
          <!-- Search widget-->
          <div class="card mb-4 " style="background-color: #DCDCDC;">
            <div class="card-header"><%= t('views.pesquisar_tags')%></div>
            <%= form_tag home_index_path, method: 'get', data: { turbo: false }  do %>
              <div class="card-body">
                <div class="input-group">
                  <%= text_field_tag :search, params[:searh], class: "form-control", id: "search-input"%>
                  <%= button_tag(value: "commit", type: 'submit', class: "btn btn-primary") do %>
                    <i class="bi bi-search-heart-fill"></i>
                  <% end %>
                </div>
                <div id="suggestions-container"></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
  </body>
</html>

app/views/accounts/user_details.html.erb
  <div class="container py-5">
  <div class="d-flex justify-content-center">
    <div class="row">
      <div class="col-lg-12">
        <div class="card mb-4" style="background-color: #DCDCDC;">
          <div class="card-body text-center">
            <%= exibir_avatar(@user.id, 150) %>
            <h5 class="my-3"><%= @user.perfil.nome %> <%= @user.perfil.sobrenome %></h5>
            <p class="text-muted mb-1">Posts: <%= @post_count %> </p>
            <p class="text-muted mb-4"><%= t('views.comentarios') %> <%= @comentarios_count %> </p>
            <div class="d-flex justify-content-center mb-2">
              <%= link_to t('buttons.editar_perfil'), edit_user_registration_path(@user), class: "btn btn-outline-primary ms-1" %>
              <%= link_to t('buttons.editar_senha'), change_password_path(@user), class: "btn btn-outline-secondary ms-1" %>
              <%= link_to "Posts", posts_details_path, class: "btn btn-outline-dark ms-1", data: { turbo: false } %>
              <%= link_to t('buttons.new_post'),new_post_path, class: "btn btn-outline-success ms-1", data: { turbo: false } %>
              <%= link_to "Upload Post",upload_post_path, class: "btn btn-outline-primary ms-1", data: { turbo: false } %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="card mb-4 " style="background-color: #DCDCDC;">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><%= t('views.nome') %></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.perfil.nome %> <%= @user.perfil.sobrenome %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><%= t('views.bio') %></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.perfil.bio %></p>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>